info:
  name: swagger
  type: http
  seq: 4

http:
  method: GET
  url: https://localhost/order/v3/api-docs
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
