spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}

  data:
    redis:
      url: ${REDIS_URL}