server:
  port: ${PORT:8080}

  tomcat:
    threads:
      max: 10

spring:
  application:
    name: microservice-identity

  profiles:
    active: ${ACTIVE_PROFILE:test}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}

    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 2

  data:
    redis:
      url: ${REDIS_URL}

  cache:
    type: redis

  rabbitmq:
    addresses: ${RABBITMQ_URL}

    listener:
      direct:
        prefetch: 20

        retry:
          enabled: true
          max-retries: 3
          multiplier: 2.0
          initial-interval: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

jwt:
  public-key: ${classpath:app.pub}
  private-key: ${classpath:app.key}