server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-identity

  profiles:
    active: ${ACTIVE_PROFILE:test}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info