services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    environment:
      SERVER_DOMAIN:

  # ----- DATA ------

  identity_db:
    image: postgres:17-alpine
    container_name: identity_db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_IDENTITY_DATABASE:-identity}
      POSTGRES_USER: ${PG_IDENTITY_USER:-identity}
      POSTGRES_PASSWORD: ${PG_IDENTITY_PASSWORD:-identity}
    volumes:
      - identity_data:/var/lib/postgresql/data

  identity_db_scraper:
    image: prometheuscommunity/postgres-exporter
    container_name: identity_db_scraper

    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      DATA_SOURCE_URI: identity_db:5432/${PG_IDENTITY_DATABASE:-identity}?sslmode=disable
      DATA_SOURCE_USER: ${PG_IDENTITY_USER:-identity}
      DATA_SOURCE_PASS: ${PG_IDENTITY_PASSWORD:-identity}

  product_db:
    container_name: product_db
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${PG_PRODUCT_DATABASE:-product}
      MONGO_INITDB_ROOT_USERNAME: ${PG_PRODUCT_USER:-product}
      MONGO_INITDB_ROOT_PASSWORD: ${PG_PRODUCT_PASSWORD:-product}
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 500M
    volumes:
      - product_data:/data/db

  vector_db:
    image: pgvector/pgvector:pg17-trixie
    container_name: vector_db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_VECTOR_DATABASE:-vector}
      POSTGRES_USER: ${PG_VECTOR_USER:-vector}
      POSTGRES_PASSWORD: ${PG_VECTOR_PASSWORD:-vector}
    volumes:
      - vector_data:/var/lib/postgresql/data

  pricing_db:
    image: postgres:17-alpine
    container_name: pricing_db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_PRICING_DATABASE:-pricing}
      POSTGRES_USER: ${PG_PRICING_USER:-pricing}
      POSTGRES_PASSWORD: ${PG_PRICING_PASSWORD:-pricing}
      GRAPH_HOPPER_API_KEY:
    volumes:
      - pricing_data:/var/lib/postgresql/data

  order_db:
    image: postgres:17-alpine
    container_name: order_db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_ORDER_DATABASE:-order}
      POSTGRES_USER: ${PG_ORDER_USER:-order}
      POSTGRES_PASSWORD: ${PG_ORDER_PASSWORD:-order}
      GRAPH_HOPPER_API_KEY:
    volumes:
      - order_data:/var/lib/postgresql/data

  notification_db:
    image: postgres:17-alpine
    container_name: notification_db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_NOTIFICATION_DATABASE:-notification}
      POSTGRES_USER: ${PG_NOTIFICATION_USER:-notification}
      POSTGRES_PASSWORD: ${PG_NOTIFICATION_PASSWORD:-notification}
    volumes:
      - notification_data:/var/lib/postgresql/data

  payment_db:
    image: postgres:17-alpine
    container_name: payment_db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_PAYMENT_DATABASE:-payment}
      POSTGRES_USER: ${PG_PAYMENT_USER:-payment}
      POSTGRES_PASSWORD: ${PG_PAYMENT_PASSWORD:-payment}
    volumes:
      - payment_data:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:7.4-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 400M
    volumes:
      - cache_data:/data

  # ----- COMMUNICATION ------

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq-local
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro,z
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro,z
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}

  # ----- OBSERVABILITY ------
  cadvisor:
    #    image: gcr.io/cadvisor/cadvisor:v0.49.1
    image: ghcr.io/google/cadvisor:0.57.0
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: "prometheus"
    restart: unless-stopped
    depends_on:
      identity_db_scraper:
        condition: service_started
      cadvisor:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - prometheus_data:/var/prometheus:Z

  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: "grafana"
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: ${GRAFANA_SMTP_GMAIL}
      GF_SMTP_PASSWORD: ${GRAFANA_SMTP_PASSWORD}
      GF_SMTP_FROM_ADDRESS: ${GRAFANA_SMTP_GMAIL}
      GF_SMTP_FROM_MESSAGE: Grafana Alerts
      GF_SMTP_STARTTLS_POLICY: MandatoryStartTLS
    volumes:
      - ./observability/grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml:Z
      - grafana_data:/var/lib/grafana:Z


  # ----- MICROSERVICES -----

  identity:
    container_name: identity_service
    build:
      context: microservice-identity/
      dockerfile: Dockerfile
    depends_on:
      identity_db:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 600M
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
      PG_URL: jdbc:postgresql://identity_db:5432/${PG_IDENTITY_DATABASE:-identity}
      PG_USER: ${PG_IDENTITY_USER:-identity}
      PG_PASSWORD: ${PG_IDENTITY_PASSWORD:-identity}
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}
      REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: prod

  product:
    container_name: product_service
    build:
      context: microservice-product/
      dockerfile: Dockerfile
    depends_on:
      product_db:
        condition: service_started
      vector_db:
        condition: service_started
      rabbitmq:
        condition: service_started
      cache:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 600M
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
      MONGO_HOST: product_db
      MONGO_PORT: 27017
      MONGO_USERNAME: ${PG_PRODUCT_USER:-product}
      MONGO_PASSWORD: ${PG_PRODUCT_PASSWORD:-product}
      MONGO_DATABASE: ${PG_PRODUCT_DATABASE:-product}
      PG_URL: jdbc:postgresql://vector_db:5432/${PG_VECTOR_DATABASE:-vector}
      PG_USER: ${PG_VECTOR_USER:-vector}
      PG_PASSWORD: ${PG_VECTOR_PASSWORD:-vector}
      REDIS_URL: redis://cache:6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}
      OPENAI_API_KEY:
      ACTIVE_PROFILE: prod

  pricing:
    container_name: pricing_service
    build:
      context: microservice-pricing
      dockerfile: Dockerfile.jvm.build
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_started
      pricing_db:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_URL: jdbc:postgresql://pricing_db:5432/${PG_PRICING_DATABASE:-pricing}
      PG_USER: ${PG_PRICING_USER:-pricing}
      PG_PASSWORD: ${PG_PRICING_PASSWORD:-pricing}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}

  order:
    container_name: order_service
    build:
      context: microservice-order/
      dockerfile: Dockerfile
    depends_on:
      order_db:
        condition: service_started
      cache:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_URL: jdbc:postgresql://order_db:5432/${PG_ORDER_DATABASE:-order}
      PG_USER: ${PG_ORDER_USER:-order}
      PG_PASSWORD: ${PG_ORDER_PASSWORD:-order}
      REDIS_URL: redis://cache:6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}
      GRAPH_HOPPER_API_KEY:
      ACTIVE_PROFILE: prod

  notification:
    container_name: notification_service
    build:
      context: microservice-notification-v2/
      dockerfile: Dockerfile.jvm.build
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    depends_on:
      notification_db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PG_URL: jdbc:postgresql://notification_db:5432/${PG_NOTIFICATION_DATABASE:-notification}
      PG_USER: ${PG_NOTIFICATION_USER:-notification}
      PG_PASSWORD: ${PG_NOTIFICATION_PASSWORD:-notification}
      AUTH_PUBLIC_KEY_URL: http://identity:8080/.well-known/jwks.json
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}

  payment:
    container_name: payment_worker
    build:
      context: worker-payment
      dockerfile: Dockerfile.jvm.build
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_started
      payment_db:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_URL: jdbc:postgresql://payment_db:5432/${PG_PAYMENT_DATABASE:-payment}
      PG_USER: ${PG_PAYMENT_USER:-payment}
      PG_PASSWORD: ${PG_PAYMENT_PASSWORD:-payment}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}

volumes:
  caddy_data:
  caddy_config:
  identity_data:
  product_data:
  vector_data:
  pricing_data:
  order_data:
  cache_data:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
  notification_data:
  payment_data: