services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    environment:
      SERVER_DOMAIN:

# ----- DATA ------

  identity_db:
    image: postgres:17-alpine
    container_name: identity_db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_IDENTITY_DATABASE}
      POSTGRES_USER: ${PG_IDENTITY_USER}
      POSTGRES_PASSWORD: ${PG_IDENTITY_PASSWORD}
      GRAPH_HOPPER_API_KEY:
    volumes:
      - identity_data:/var/lib/postgresql/data

  product_db:
    image: postgres:17-alpine
    container_name: product_db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_PRODUCT_DATABASE}
      POSTGRES_USER: ${PG_PRODUCT_USER}
      POSTGRES_PASSWORD: ${PG_PRODUCT_PASSWORD}
    volumes:
      - product_data:/var/lib/postgresql/data

  order_db:
    image: postgres:17-alpine
    container_name: order_db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_ORDER_DATABASE}
      POSTGRES_USER: ${PG_ORDER_USER}
      POSTGRES_PASSWORD: ${PG_ORDER_PASSWORD}
    volumes:
      - order_data:/var/lib/postgresql/data

  notification_db:
    image: postgres:17-alpine
    container_name: notification_db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_NOTIFICATION_DATABASE}
      POSTGRES_USER: ${PG_NOTIFICATION_USER}
      POSTGRES_PASSWORD: ${PG_NOTIFICATION_PASSWORD}
    volumes:
      - notification_data:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:7.4-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - cache_data:/data

# ----- COMMUNICATION ------

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq-local
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro,z
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro,z
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

# ----- OBSERVABILITY ------

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: "prometheus"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - prometheus_data:/var/prometheus:Z

  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: "grafana"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_HTTP_ADDR: "0.0.0.0"
    volumes:
      - ./observability/grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml:Z
      - grafana_data:/var/lib/grafana:Z


# ----- MICROSERVICES ------

  identity:
    container_name: identity_service
    build:
      context: microservice-identity/
      dockerfile: Dockerfile
    depends_on:
      identity_db:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_IDENTITY_DATABASE:
      PG_IDENTITY_USER:
      PG_IDENTITY_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity_db:5432/${PG_IDENTITY_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${PG_IDENTITY_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_IDENTITY_PASSWORD}
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev

  product:
    container_name: product_service
    build:
      context: microservice-product/
      dockerfile: Dockerfile
    depends_on:
      product_db:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_PRODUCT_DATABASE:
      PG_PRODUCT_USER:
      PG_PRODUCT_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATASOURCE_URL: jdbc:postgresql://product_db:5432/${PG_PRODUCT_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${PG_PRODUCT_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PRODUCT_PASSWORD}
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev

  order:
    container_name: order_service
    build:
      context: microservice-order/
      dockerfile: Dockerfile
    depends_on:
      order_db:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_PRODUCT_DATABASE:
      PG_PRODUCT_USER:
      PG_PRODUCT_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/${PG_ORDER_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${PG_ORDER_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_ORDER_PASSWORD}
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev
      GRAPH_HOPPER_API_KEY:

#  notification:
#    container_name: notification_service
#    build:
#      context: microservice-notification/
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    depends_on:
#      notification_db:
#        condition: service_started
#    environment:
#      PG_NOTIFICATION_DATABASE:
#      PG_NOTIFICATION_USER:
#      PG_NOTIFICATION_PASSWORD:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://notification_db:5432/${PG_NOTIFICATION_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${PG_NOTIFICATION_USER}
#      SPRING_DATASOURCE_PASSWORD: ${PG_NOTIFICATION_PASSWORD}
#      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
#
#      SPRING_DATA_REDIS_URL: redis://cache:6379
#      ACTIVE_PROFILE: dev

  notification-v2:
    container_name: notification_service_v2
    build:
      context: microservice-notification-v2/
      dockerfile: Dockerfile.jvm.build
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    depends_on:
      notification_db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PG_NOTIFICATION_URL: jdbc:postgresql://notification_db:5432/postgres
      PG_NOTIFICATION_USER:
      PG_NOTIFICATION_PASSWORD:
      AUTH_PUBLIC_KEY_URL: http://identity:8080/.well-known/jwks.json
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  payment:
    container_name: payment_service
    build:
      context: microservice-payment/
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_PRODUCT_DATABASE:
      PG_PRODUCT_USER:
      PG_PRODUCT_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev

volumes:
  caddy_data:
  caddy_config:
  identity_data:
  product_data:
  order_data:
  cache_data:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
  notification_data: