services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 200M
    volumes:
      - ./caddy/dev.Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

# ----- DATA ------

  identity_db:
    image: postgres:17-alpine
    container_name: identity_db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_IDENTITY_DATABASE:-identity}
      POSTGRES_USER: ${PG_IDENTITY_USER:-identity}
      POSTGRES_PASSWORD: ${PG_IDENTITY_PASSWORD:-identity}
    volumes:
      - identity_data:/var/lib/postgresql/data

  identity_db_scraper:
    image: prometheuscommunity/postgres-exporter
    container_name: identity_db_scraper
    depends_on:
      identity_db:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: identity_db:5432/${PG_IDENTITY_DATABASE:-identity}?sslmode=disable
      DATA_SOURCE_USER: ${PG_IDENTITY_USER:-identity}
      DATA_SOURCE_PASS: ${PG_IDENTITY_PASSWORD:-identity}

  product_db:
    image: pgvector/pgvector:pg17-trixie
    container_name: product_db
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_PRODUCT_DATABASE:-product}
      POSTGRES_USER: ${PG_PRODUCT_USER:-product}
      POSTGRES_PASSWORD: ${PG_PRODUCT_PASSWORD:-product}
    volumes:
      - product_data:/var/lib/postgresql/data

  product_db_scraper:
    image: prometheuscommunity/postgres-exporter
    container_name: product_db_scraper
    depends_on:
      product_db:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: product_db:5432/${PG_PRODUCT_DATABASE:-product}?sslmode=disable
      DATA_SOURCE_USER: ${PG_PRODUCT_USER:-product}
      DATA_SOURCE_PASS: ${PG_PRODUCT_PASSWORD:-product}

  order_db:
    image: postgres:17-alpine
    container_name: order_db
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_ORDER_DATABASE:-order}
      POSTGRES_USER: ${PG_ORDER_USER:-order}
      POSTGRES_PASSWORD: ${PG_ORDER_PASSWORD:-order}
      GRAPH_HOPPER_API_KEY:
    volumes:
      - order_data:/var/lib/postgresql/data

  notification_db:
    image: postgres:17-alpine
    container_name: notification_db
    ports:
      - "5435:5432"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      POSTGRES_DB: ${PG_NOTIFICATION_DATABASE:-notification}
      POSTGRES_USER: ${PG_NOTIFICATION_USER:-notification}
      POSTGRES_PASSWORD: ${PG_NOTIFICATION_PASSWORD:-notification}
    volumes:
      - notification_data:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:7.4-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 400M
    volumes:
      - cache_data:/data

# ----- COMMUNICATION ------

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq-local
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 400M
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro,z
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro,z
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}

# ----- OBSERVABILITY ------
  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.49.1
    image: ghcr.io/google/cadvisor:0.57.0
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: 0.5

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: "prometheus"
    restart: unless-stopped
    depends_on:
      identity_db_scraper:
        condition: service_started
      product_db_scraper:
        condition: service_started
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - prometheus_data:/var/prometheus:Z

  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: "grafana"
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - ./observability/grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml:Z
      - grafana_data:/var/lib/grafana:Z


# ----- MICROSERVICES -----

  identity:
    container_name: identity_service
    build:
      context: microservice-identity/
      dockerfile: Dockerfile
    depends_on:
      identity_db:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 600M
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
      PG_IDENTITY_DATABASE:
      PG_IDENTITY_USER:
      PG_IDENTITY_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity_db:5432/${PG_IDENTITY_DATABASE:-identity}
      SPRING_DATASOURCE_USERNAME: ${PG_IDENTITY_USER:-identity}
      SPRING_DATASOURCE_PASSWORD: ${PG_IDENTITY_PASSWORD:-identity}
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev

  product:
    container_name: product_service
    build:
      context: microservice-product/
      dockerfile: Dockerfile
    depends_on:
      product_db:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 600M
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
      PG_PRODUCT_DATABASE:
      PG_PRODUCT_USER:
      PG_PRODUCT_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATASOURCE_URL: jdbc:postgresql://product_db:5432/${PG_PRODUCT_DATABASE:-product}
      SPRING_DATASOURCE_USERNAME: ${PG_PRODUCT_USER:-product}
      SPRING_DATASOURCE_PASSWORD: ${PG_PRODUCT_PASSWORD:-product}
      OPENAI_API_KEY:
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev

  order:
    container_name: order_service
    build:
      context: microservice-order/
      dockerfile: Dockerfile
    depends_on:
      order_db:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      PG_PRODUCT_DATABASE:
      PG_PRODUCT_USER:
      PG_PRODUCT_PASSWORD:
      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/${PG_ORDER_DATABASE:-order}
      SPRING_DATASOURCE_USERNAME: ${PG_ORDER_USER:-order}
      SPRING_DATASOURCE_PASSWORD: ${PG_ORDER_PASSWORD:-order}
      SPRING_DATA_REDIS_URL: redis://cache:6379
      ACTIVE_PROFILE: dev
      GRAPH_HOPPER_API_KEY:

  notification:
    container_name: notification_service
    build:
      context: microservice-notification-v2/
      dockerfile: Dockerfile.jvm.build
    restart: unless-stopped
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    depends_on:
      notification_db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PG_NOTIFICATION_URL: jdbc:postgresql://notification_db:5432/${PG_NOTIFICATION_DATABASE:-notification}
      PG_NOTIFICATION_USER:
      PG_NOTIFICATION_PASSWORD:
      AUTH_PUBLIC_KEY_URL: http://identity:8080/.well-known/jwks.json
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}

#  notification:
#    container_name: notification_service
#    build:
#      context: microservice-notification/
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    depends_on:
#      notification_db:
#        condition: service_started
#    ports:
#      - "8083:8080"
#    environment:
#      PG_NOTIFICATION_DATABASE:
#      PG_NOTIFICATION_USER:
#      PG_NOTIFICATION_PASSWORD:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://notification_db:5432/${PG_NOTIFICATION_DATABASE:-notification}
#      SPRING_DATASOURCE_USERNAME: ${PG_NOTIFICATION_USER:-notification}
#      SPRING_DATASOURCE_PASSWORD: ${PG_NOTIFICATION_PASSWORD:-notification}
#      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
#      SPRING_DATA_REDIS_URL: redis://cache:6379
#      ACTIVE_PROFILE: dev

#  payment:
#    container_name: payment_service
#    build:
#      context: microservice-payment/
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "8084:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: 0.5
#          memory: 600M
#    environment:
#      SPRING_RABBITMQ_ADDRESSES: amqp://admin:admin@rabbitmq:5672/
#      ACTIVE_PROFILE: dev

  payment:
    container_name: payment_worker
    build:
      context: worker-payment
      dockerfile: Dockerfile.jvm.build
    restart: unless-stopped
    ports:
      - "8084:8080"
    depends_on:
      rabbitmq:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 600M
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}

volumes:
  caddy_data:
  caddy_config:
  identity_data:
  product_data:
  order_data:
  cache_data:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
  notification_data: