quarkus.http.port=8080

mp.messaging.connector.smallrye-rabbitmq.host=${RABBITMQ_HOST}
mp.messaging.connector.smallrye-rabbitmq.port=${RABBITMQ_PORT}
mp.messaging.connector.smallrye-rabbitmq.username=${RABBITMQ_USER}
mp.messaging.connector.smallrye-rabbitmq.password=${RABBITMQ_PASSWORD}

mp.messaging.incoming.generate-payment.connector=smallrye-rabbitmq
mp.messaging.incoming.generate-payment.queue.name=payment.generate_payment
mp.messaging.incoming.generate-payment.exchange.name=""
mp.messaging.incoming.generate-payment.queue.declare=false

mp.messaging.outgoing.payment-generated.connector=smallrye-rabbitmq
mp.messaging.outgoing.payment-generated.exchange.name=payment.generated.fanout
mp.messaging.outgoing.payment-generated.exchange.type=fanout
mp.messaging.outgoing.payment-generated.exchange.declare=false

mp.messaging.outgoing.payment-confirmed.connector=smallrye-rabbitmq
mp.messaging.outgoing.payment-confirmed.exchange.name=payment.confirmed.fanout
mp.messaging.outgoing.payment-confirmed.exchange.type=fanout
mp.messaging.outgoing.payment-confirmed.exchange.declare=false
