quarkus.http.port=8080

# ----- SECURITY -----

mp.jwt.verify.publickey.location=${AUTH_PUBLIC_KEY_URL}
smallrye.jwt.path.groups=roles

# ----- PERSISTENCE -----

quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${PG_URL}
quarkus.datasource.username=${PG_USER:postgres}
quarkus.datasource.password=${PG_PASSWORD:postgres}

# ----- MESSAGING -----

mp.messaging.connector.smallrye-rabbitmq.host=${RABBITMQ_HOST}
mp.messaging.connector.smallrye-rabbitmq.port=${RABBITMQ_PORT}
mp.messaging.connector.smallrye-rabbitmq.username=${RABBITMQ_USER}
mp.messaging.connector.smallrye-rabbitmq.password=${RABBITMQ_PASSWORD}

mp.messaging.outgoing.price-checked.connector=smallrye-rabbitmq
mp.messaging.outgoing.price-checked.exchange.name=pricing.topic
mp.messaging.outgoing.price-checked.exchange.type=topic
mp.messaging.outgoing.price-checked.exchange.declare=false
mp.messaging.outgoing.price-checked.default-routing-key=price.checked

mp.messaging.outgoing.price-updated.connector=smallrye-rabbitmq
mp.messaging.outgoing.price-updated.exchange.name=pricing.topic
mp.messaging.outgoing.price-updated.exchange.type=topic
mp.messaging.outgoing.price-updated.exchange.declare=false
mp.messaging.outgoing.price-updated.default-routing-key=price.updated

mp.messaging.incoming.product-created.connector=smallrye-rabbitmq
mp.messaging.incoming.product-created.queue.name=pricing.register_product
mp.messaging.incoming.product-created.queue.declare=false
mp.messaging.incoming.product-created.exchange.name=""
mp.messaging.incoming.product-created.exchange.declare=false

mp.messaging.incoming.product-deleted.connector=smallrye-rabbitmq
mp.messaging.incoming.product-deleted.queue.name=pricing.delete_product
mp.messaging.incoming.product-deleted.queue.declare=false
mp.messaging.incoming.product-deleted.exchange.name=""
mp.messaging.incoming.product-deleted.exchange.declare=false

mp.messaging.incoming.apply-price.connector=smallrye-rabbitmq
mp.messaging.incoming.apply-price.queue.name=pricing.apply_price
mp.messaging.incoming.apply-price.queue.declare=false
mp.messaging.incoming.apply-price.exchange.name=""
mp.messaging.incoming.apply-price.exchange.declare=false
