server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-identity

  profiles:
    active: ${ACTIVE_PROFILE:test}

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity:8080/.well-known/jwks.json

  data:
    web:
      pageable:
        max-page-size: 20

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
      minimum-idle: 2

  rabbitmq:
    listener:
      simple:
        prefetch: 20
        retry:
          enabled: true
          max-retries: 3
          multiplier: 1.5
          initial-interval: 500ms
          max-interval: 2000ms

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:test}
      embedding:
        options:
          model: text-embedding-3-small

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

broker:
  queues:
    refundProduct:
      name: product.refund

  exchanges:
    orderTopic:
      name: order.topic

feign:
  clients:
    sales_order:
      url: http://order:8080