server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-identity

  profiles:
    active: ${ACTIVE_PROFILE:test}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity:8080/.well-known/jwks.json

  rabbitmq:
    listener:
      direct:
        prefetch: 20
        retry:
          enabled: true
          max-retries: 10
          initial-interval: 2000ms
          multiplier: 2.0

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

broker:
  queues:
    createOrder:
      name: order.create_order
    refundItems:
      name: product.refund_items

feign:
  clients:
    sales_order:
      url: http://order:8080