spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}

  mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    database: ${MONGO_DATABASE}
    authentication-database: admin

  data:
    redis:
      url: ${REDIS_URL}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT}
      region:
        static: ${AWS_REGION}
      credentials:
        secret-key: ${AWS_SECRET_KEY}
        access-key: ${AWS_ACCESS_KEY}
      s3:
        path-style-access-enabled: true