spring:
  application:
    name: microservice-identity

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password: dev

  flyway:
    enabled: true