quarkus.http.port=8080

mp.jwt.verify.publickey.location=${AUTH_PUBLIC_KEY_URL}

mp.messaging.connector.smallrye-rabbitmq.host=${RABBITMQ_HOST}
mp.messaging.connector.smallrye-rabbitmq.port=${RABBITMQ_PORT}
mp.messaging.connector.smallrye-rabbitmq.username=${RABBITMQ_USER}
mp.messaging.connector.smallrye-rabbitmq.password=${RABBITMQ_PASSWORD}

mp.messaging.incoming.payment-generated.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-generated.queue.name=notification.notify_payment_generated
mp.messaging.incoming.payment-generated.exchange.name=""
mp.messaging.incoming.payment-generated.queue.declare=false
mp.messaging.incoming.payment-generated.exchange.declare=false

mp.messaging.incoming.payment-confirmed.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-confirmed.queue.name=notification.notify_payment_confirmed
mp.messaging.incoming.payment-confirmed.exchange.name=""
mp.messaging.incoming.payment-confirmed.queue.declare=false
mp.messaging.incoming.payment-confirmed.exchange.declare=false

mp.messaging.incoming.payment-timeout.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-timeout.queue.name=notification.notify_payment_timeout
mp.messaging.incoming.payment-timeout.exchange.name=""
mp.messaging.incoming.payment-timeout.queue.declare=false
mp.messaging.incoming.payment-timeout.exchange.declare=false

mp.messaging.incoming.payment-refunded.connector=smallrye-rabbitmq
mp.messaging.incoming.payment-refunded.queue.name=notification.notify_payment_refunded
mp.messaging.incoming.payment-refunded.exchange.name=""
mp.messaging.incoming.payment-refunded.queue.declare=false
mp.messaging.incoming.payment-refunded.exchange.declare=false

mp.messaging.incoming.order-canceled.connector=smallrye-rabbitmq
mp.messaging.incoming.order-canceled.queue.name=notification.notify_canceled_order
mp.messaging.incoming.order-canceled.exchange.name=""
mp.messaging.incoming.order-canceled.queue.declare=false
mp.messaging.incoming.order-canceled.exchange.declare=false

mp.messaging.incoming.shipping-dispatched.connector=smallrye-rabbitmq
mp.messaging.incoming.shipping-dispatched.queue.name=notification.notify_shipping_dispatched
mp.messaging.incoming.shipping-dispatched.exchange.name=""
mp.messaging.incoming.shipping-dispatched.exchange.declare=false
mp.messaging.incoming.shipping-dispatched.queue.declare=false

quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${PG_URL}
quarkus.datasource.username=${PG_USER}
quarkus.datasource.password=${PG_PASSWORD}

quarkus.swagger-ui.always-include=true

#%test.quarkus.flyway.enabled=false
#%test.quarkus.hibernate-orm.scripts.generation=drop-and-create
#%test.quarkus.datasource.db-kind=h2
#%test.quarkus.datasource.url=test
#%test.quarkus.datasource.username=test
#%test.quarkus.datasource.password=test