server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-identity

  profiles:
    active: ${ACTIVE_PROFILE:test}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity:8080/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info