server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-order

  profiles:
    active: ${ACTIVE_PROFILE:test}

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity:8080/.well-known/jwks.json

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  rabbitmq:
    listener:
      simple:
        prefetch: 20
        retry:
          enabled: true
          max-retries: 10
          initial-interval: 2000ms
          multiplier: 2.0

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

broker:
  exchanges:
    orderTopic:
      name: order.topic

  queues:
    createOrder:
      name: order.create_order

    createShipping:
      name: order.create_shipping

    cancelShipments:
      name: order.cancel_shipments

    confirmPayment:
      name: order.confirm_payment

    handlePaymentTimeout:
      name: order.handle_payment_timeout

graphHopperClient:
  apiKey: ${GRAPH_HOPPER_API_KEY:test}