server:
  port: ${PORT:8080}

spring:
  application:
    name: microservice-identity

  profiles:
    active: ${ACTIVE_PROFILE:test}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity:8080/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

broker:
  exchanges:
    paymentGeneratedFanout:
      name: payment.generated.fanout

    paymentConfirmedFanout:
      name: payment.confirmed.fanout

  queues:
    createOrder:
      name: order.create_order

    generatePayment:
      name: payment.generate_payment

    handlePaymentTimeout:
      name: order.handle_payment_timeout

    confirmOrderPayment:
      name: order.confirm_order_payment