spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}