info:
  name: Product
  type: graphql
  seq: 8

graphql:
  method: POST
  url: https://localhost/product/api/v2/graphql
  body:
    query: |-
      query {
      	product(id: "6aaeec3353d464ad7aa07e9a") {
          id
          name
          description
          images {
            id
            url
          }
          SKUs {
            name
            SKU
            currentPrice {
              label
      				value
            }
            stock
          }
          createdAt
          createdBy
          updatedAt
          updatedBy
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: true
